name: raise_by_agriva
description: RAISE by AGRIVA - Rice AI Stress Evaluator
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  http: ^1.2.2
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  supabase_flutter: ^2.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
